### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by mbadrala** [mbadrala/unity_feedbacks#1]
### Camera

- [ ] Shake : shakes the camera over time
- [ ] Zoom : lets you zoom in or out when the feedback plays
- [ ] Flash : flash an image on screen, or simply a color for a short duration
- [ ] Fade : fade an image in or out, useful for transitions
